#!/bin/bash

# Install dependencies
sudo dnf install -y make gcc zlib-devel bzip2 bzip2-devel readline-devel sqlite sqlite-devel openssl-devel tk-devel libffi-devel xz-devel libuuid-devel gdbm-devel libnsl2-devel

# Install pyenv
git clone https://github.com/pyenv/pyenv ~/.pyenv
