#!/bin/bash

sudo dnf install -y gcc patch make bzip2 openssl-devel libyaml-devel libffi-devel readline-devel zlib-devel gdbm-devel ncurses-devel

# Install rbenv
git clone https://github.com/rbenv/rbenv ~/.rbenv
git clone https://github.com/rbenv/ruby-build ~/.ruby-build
