# Key bindings
set -g prefix C-t

unbind C-b

# Color settings
set-option -g default-terminal screen-256color
set -g terminal-overrides 'xterm:colors=256'

setw -g status-style fg=#FFFFFF,bg=#111111

# Powerline status bar
source ~/.config/powerline/powerline.conf
run-shell "powerline-daemon -q"
