# tmux plugin managet
run '/usr/share/tmux-plugin-manager-git/tpm'

# Key bindings
set -g prefix C-t

unbind C-b

# Color settings
set-option -g default-terminal screen-256color
set -g terminal-overrides 'xterm:colors=256'

set-option -g status-interval 1 

set-option -g status-justify 'centre'

set-option -g status-bg '#F0F0F0'
set-option -g status-fg '#494B53'

set-option -g status-left-length 90
set-option -g status-left '#[fg=#F0F0F0]#[bg=#50A14F]Session: #S '

set-window-option -g window-status-current-format '#[fg=#494B53]#[bg=#D0D0D0]#I: #W '
set-window-option -g window-status-format '[#[fg=#494B53]#[bg=F0F0F0]#I: #W] '

set-option -g status-right-length 90
set-option -g status-right '#[fg=#494B53]#[bg=#D0D0D0] #h'

set -g @plugin 'tmux-plugins/tmux-sensible'

