# vim:ft=kitty

font_family HackGen Console
font_size 12.0

remember_window_size  no
# initial_window_width  1920
# initial_window_height 1080
initial_window_width  1280
initial_window_height 720

window_padding_width 3

background_opacity 0.75
background_blur 1

include current-theme.conf
