# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](black)\
$directory\
$python\
[](black)
$character
"""

right_format= """
[](black)
$time
[](black)
"""

add_newline = false
palette = 'nordfox'

[package]
disabled = true

[palettes.nordfox]
foreground = '#cdcecf'
separator = '#60728a'
black = '#3b4252'
red = '#bf616a'
blue = '#81a1c1'
cyan = '#88c0d0'

[directory]
truncation_length = 0
truncate_to_repo = false
format = '[ $read_only]($read_only_style)[$path ]($style)'
style = 'bg:black fg:foreground'
read_only = '󰌾 '
read_only_style = 'bg:black fg:red'
truncation_symbol = '.../'
use_os_path_sep = false

[python]
format = '[ ](bg:black fg:separator)[${symbol} ${version} ]($style)'
version_format = '${raw}'
symbol = '' # nf-dev-python
style = 'bg:black fg:cyan bold'
