#!/bin/bash

# Set nvm version
set -U nvm_default_version v18.12.1

# Config for AVR_Rust
set -Ux AVR_CPU_FREQUENCY_HZ 16000000

# Config for pyenv
set -Ux PYENV_ROOT $HOME/.pyenv
set -Ux PYTHON_KEYRING_BACKEND keyring.backends.null.Keyring

# For Python modules
fish_add_path -a $HOME/.local/bin

# For pyenv
fish_add_path -a $PYENV_ROOT/shims

# For Rust
fish_add_path -a $HOME/.cargo/bin

# Install fish plugins
fisher install jorgebucaran/fisher jorgebucaran/nvm.fish oh-my-fish/theme-bobthefish

# Install nvm
nvm install

# Install poetry
pip install poetry
poetry config virtualenvs.in-project true

# Install Python using pyenv
pyenv install 3.8.16 --verbose
pyenv install 3.11.0 --verbose
