#!/bin/bash

DOTDIR="$HOME/dotfiles"
CONFDIR="$HOME/.config"

function link_file(){
    local target=$1
    local put_locate=$2

    if [ -e "${put_locate}/${target}" ]; then
        rm -rf "${put_locate}/${target}"
    fi
    ln -sf "$DOTDIR/${target}" "${put_locate}/${target}"
}

# Create XDG_CONFIG_DIR if does not exists
if [ ! -e "$CONFDIR" ]; then
    mkdir "$CONFDIR"
fi

# Put config files on HOME
link_file ".gitconfig" "$HOME"
link_file ".nvmrc" "$HOME"

# Put config files on XDG_CONFIG_DIR
link_file "nvim" "$CONFDIR"
link_file "tmux" "$CONFDIR"
link_file "fish" "$CONFDIR"

cd ~/

sudo apt update
sudo apt upgrade -y

sudo apt install -y \
    build-essential \
    vim \
    texlive-full \
    python3 python3-pip python3-venv python-is-python3 \
    ppa-purge \
    curl \
    libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev curl llvm libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev \
    ninja-build gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip curl doxygen \
    neovim

# Install Python modules
pip install poetry

# Install pyenv
git clone https://github.com/pyenv/pyenv ~/.pyenv

mkdir -p ~/Development
