#!/bin/bash

cd ~/

sudo apt update
sudo apt upgrade -y

sudo apt install -y \
    build-essential \
    vim \
    texlive-full \
    python3 python3-pip python3-venv python-is-python3 \
    ppa-purge \
    curl \
    libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev curl llvm libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev \
    ninja-build gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip curl doxygen

# Install neovim
git clone https://github.com/neovim/neovim -b release-8.0 ~/neovim
git clone --depth 1 https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim

# Install Python modules
pip install poetry

# Install pyenv
git clone https://github.com/pyenv/pyenv ~/.pyenv

mkdir -p ~/Development

ln -sf ~/dotfiles/nvim ~/.config/nvim
ln -sf ~/dotfiles/emacs ~/.config/emacs
ln -sf ~/dotfiles/tmux ~/.config/tmux

ln -sf ~/dotfiles/fish/config.fish ~/.config/fish/config.fish
ln -sf ~/dotfiles/fish/fish_variables ~/.config/fish/fish_variables

ln -sf ~/dotfiles/.Xresources ~/.Xresources
ln -sf ~/dotfiles/.Xmodmap ~/.Xmodmap
ln -sf ~/dotfiles/.gitconfig ~/.gitconfig
