#!/bin/bash

cd ~/

sudo apt update
sudo apt upgrade -y

sudo apt install -y \
    build-essential \
    vim \
    texlive-full \
    python3 python3-pip python3-venv \
    ppa-purge \
    curl \
    libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev curl llvm libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev \
    ninja-build gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip curl doxygen

# Install neovim
git clone https://github.com/neovim/neovim -b release-8.0 ~/neovim
cd ~/neovim/
make -j17 CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install
cd ~/
git clone --depth 1 https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim

# Install fish shell
sudo add-apt-repository ppa:fish-shell/release-3
sudo apt update
sudo apt install -y fish

# Install Python modules
pip install poetry

# Install pyenv
git clone https://github.com/pyenv/pyenv ~/.pyenv
pyenv install 3.8.16 3.11.0

# Install Rust Programming Language
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

# Change shell
chsh -s $(which fish)

mkdir -p ~/.config/fish
mkdir -p ~/Development

ln -sf ~/dotfiles/nvim ~/.config/nvim
ln -sf ~/dotfiles/emacs ~/.config/emacs
ln -sf ~/dotfiles/tmux ~/.config/tmux

ln -sf ~/dotfiles/fish/config.fish ~/.config/fish/config.fish
ln -sf ~/dotfiles/fish/fish_variables ~/.config/fish/fish_variables
