#!/usr/bin/fish

# Install fisherman
curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher

# Theme
fisher install ilancosman/tide@v5

# pyenv
set -Ux PYENV_ROOT $HOME/.pyenv

fish_add_path -a $PYENV_ROOT/bin
fish_add_path -a $PYENV_ROOT/shims

fisher install jorgebucaran/nvm.fish
set -U nvm_default_version v18.13.0
