#!/bin/bash -e

# Xorg
sudo pacman -S xorg-server xorg-apps xorg-xmodmap xorg-xinit --noconfirm

# Window manager
sudo pacman -S i3-gaps i3status i3lock i3blocks --noconfirm

# Misc
sudo pacman -S xterm rofi pcmanfm gvfs udisks2 fwupd --noconfirm

# Shell
# sudo pacman -S fish fisher --noconfirm
sudo pacman -S zsh --noconfirm

# zsh plugins
git clone https://github.com/zsh-users/zsh-syntax-highlighting ~/.zsh/zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-autosuggestions ~/.zsh/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-history-substring-search ~/.zsh/zsh-history-substring-search
git clone https://github.com/romkatv/powerlevel10k ~/.zsh/powerlevel10k

# For C/C++
sudo pacman -S gcc gdb clang --noconfirm

# For Rust
sudo pacman -S rustup rust-analyzer --noconfirm
rustup default stable

# AUR helper
git clone https://aur.archlinux.org/paru ~/paru
cd ~/paru
makepkg -si --noconfirm
cd ~/
rm ~/paru -rf

# Japanese IME
paru -S ibus-mozc --noconfirm

# Editor
sudo pacman -S neovim emacs --noconfirm
paru -S \
    nvim-packer-git emacs-mozc \
    visual-studio-code-bin --noconfirm

# Browser
sudo pacman -S firefox --noconfirm
paru -S google-chrome microsoft-edge-stable-bin --noconfirm

# Font
paru -S \
    noto-fonts noto-fonts-extra noto-fonts-cjk noto-fonts-emoji \
    otf-cascadia-code \
    nerd-fonts-hack --noconfirm

# Python
sudo pacman -S \
    python python-pip pyenv \
    openssl zlib xz tk --noconfirm

# Poetry
export PATH="$HOME/.local/bin:$PATH"
pip install poetry
poetry config virtualenvs.in-project true

# Pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"

pyenv install 3.11.0 --verbose
pyenv install 3.8.16 --verbose

pyenv use system

# nvm
paru -S nvm --noconfirm
source "$HOME/dotfiles/config/nvm"
nvm install --lts
nvm use --lts

# Theme
paru -S arc-gtk-theme paper-icon-theme lxappearance --noconfirm

# For energy efficiency
sudo pacman -S powertop tlp tlp-rdw acpi acpi_call tpacpi-bat --noconfirm

sudo cp ~/dotfiles/tlp/performance.conf /etc/tlp.d/
sudo cp ~/dotfiles/tlp/battery-threshold.conf /etc/tlp.d/

sudo systemctl mask systemd-rfkill.service
sudo systemctl mask systemd-rfkill.socket
sudo systemctl enable tlp.service

sudo powertop --auto-tune
sudo tlp start
