# Keyboard shortcuts
set -g prefix C-x
unbind-key C-b

# Split window vertical
bind 3 split-window -h

# Split window horizontal
bind 2 split-window -v

bind-key r source-file ~/.config/tmux/tmux.conf

set -g escape-time 1

set -g base-index 1
set -g pane-base-index 1

set -g renumber-windows on

set -g default-shell /usr/bin/fish
set -g default-command /usr/bin/fish

set -g default-terminal 'screen-256color'
set -g terminal-overrides ',rxvt-unicode-256color:Tc'

set -g set-titles on
set -g set-titles-string "#T"

set -g status-interval 1

set -g status-bg colour0
set -g status-fg colour7

set -g status-left-length 100
set -g status-right-length 100

set -g status-left '#[fg=colour0,bg=colour12] #S #[fg=colour12,bg=colour0]'
# set -g status-left '#[bg=cyan] #h | #S '

set -g status-justify 'left'
set -g window-status-format '  #I  #W  '
set -g window-status-current-format '#[fg=colour0,bg=colour8] #[fg=colour15]#I  #W #[fg=colour8,bg=colour0]'
# set -g window-status-format ' #I | #W '
# set -g window-status-current-format '#[bg=grey] #I | #W '

set -g status-right '#[fg=colour7]#[fg=colour0,bg=colour7] #h '
# set -g status-right '#[bg=grey] #(date +"%Y/%m/%d (%a) | %H:%M") '
