set -g prefix C-x
unbind-key C-b

bind-key r source-file ~/.config/tmux/tmux.conf

set -g escape-time 1

set -g base-index 1
set -g pane-base-index 1

set -g renumber-windows on

set -g default-shell /usr/bin/zsh
set -g default-command /usr/bin/zsh

set -g default-terminal 'screen-256color'
set -g terminal-overrides ',xterm-256color:Tc'

set -g set-titles on
set -g set-titles-string "#T"

set -g status-interval 1

set -g status-bg '#3b4252'
set -g status-fg '#d8dee9'

set -g status-left-length 100
set -g status-right-length 100

set -g status-left '#[fg=#2e3440,bg=#81a1c1] #h  #S #[fg=#81a1c1,bg=#3b4252]'

set -g status-justify 'left'
set -g window-status-format '  #I  #W  '
set -g window-status-current-format '#[fg=#3b4252,bg=#e5e9f0] #I  #W #[fg=#e5e9f0,bg=#3b4252]'

set -g status-right '#[fg=#4c566a]#[fg=#d8dee9,bg=#4c566a] #(date +"%Y/%m/%d (%a)  %H:%M") '
