# Key bindings
set -g prefix C-x
unbind-key C-b

bind-key r source-file ~/.config/tmux/tmux.conf

set -g escape-time 1

set -g base-index 1
setw -g pane-base-index 1

set -g renumber-windows on

# Default shell
set -g default-shell /usr/bin/zsh
set -g default-command /usr/bin/zsh

# Color settings
set-option -g default-terminal 'screen-256color'
set -g terminal-overrides ',xterm-256color:Tc'

set -g set-titles on
set -g set-titles-string "#T"

set-option -g status-interval 1 

set-option -g status-bg white
set-option -g status-fg black

set-option -g status-left-length 100
set-option -g status-right-length 100

set-option -g status-left '#[fg=black,bg=cyan] #h | #S  '

set-option -g status-justify 'centre'
set-window-option -g window-status-format '#[fg=black,bg=white] #I | #W '
set-window-option -g window-status-current-format '#[fg=black,bg=grey] #I | #W '

set-option -g status-right '#[fg=white,bg=black] #(date +"%Y/%m/%d (%a) | %H:%M") '
