# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  powerManagement.cpuFreqGovernor = "performance";

  hardware = {
    cpu.amd.updateMicrocode = true;

    # iGPU (Radeon 780M) の Vulkan (RADV) ドライバ
    graphics.enable = true;
  };

  # systemd サービス (ollama / open-webui) からも Vulkan ICD を
  # ローダ既定の /usr/share/vulkan/icd.d 経由で発見できるようにする
  environment.systemPackages = with pkgs; [
    mesa
  ];
}
